### ISSUE TITLE
Предполагаю, что скорость ветра показывает в футах в сек

### ISSUE THREAD

**Issue by ckfn4czc** [Limych/ha-gismeteo#101]
Добрый день.

Версия 2.3.4.

Предполагаю, что скорость ветра написано, что 18 m/s, а по факту в футах.
![image](https://user-images.githubusercontent.com/13085792/149866692-311306f7-527c-4a52-a314-0caef0ee4276.png)

Если привести из футов в метры - становится похожим на правду = 6.6, что округленно 7:
![image](https://user-images.githubusercontent.com/13085792/149866874-de651e60-a197-4e29-b6b2-37b97579fdd4.png)

С уважением, Дмитрий.

**Comment by ntguest** [comment]
значение в км/ч, а ед.изм. м/с

**Comment by Limych** [comment]
Вы уверены, что ошибка в сенсоре, а не в Вашем информере?
18 метров в секунду — это очень крепкий ветер: «Ветер ломает сучья деревьев, идти против ветра очень трудно» (ист.: https://meteoinfo.ru/bofort)

Сенсор ничего не изобретает, а лишь показывает данные, как они приходят с сайта Гисметео. И скорость ветра приходит именно в метрах в секунду.

Если же Вы считаете, что всё же в моём коде ошибка, извольте, пожалуйста, оформить багрепорт в соответствии с шаблоном, который предоставляется. Пока же я не вижу ошибки (за недостаточностью предоставленной информации для её воспроизведения), потому данный issue я закрываю. Уж не обессудьте...
