### ISSUE TITLE
Road weather support

### ISSUE THREAD

**Issue by dec0dOS** [Limych/ha-gismeteo#11]
Hello. Thanks for awesome project!

Is it possible to add road weather support? 

<img width="760" alt="Снимок экрана 2021-01-03 в 16 30 04" src="https://user-images.githubusercontent.com/14824142/103479796-280f3e00-4de1-11eb-9fcc-3c4f2c18646b.png">

**Comment by Limych** [comment]
I'm sorry, but only the information that is already provided by the component is available through the Gismeteo API.  There is nothing extra there.  As well as there is no way to show anything additional in the weather object.

As far as I understand, road conditions can be calculated based on available weather forecasts.
