### ISSUE TITLE
allergy. pollen

### ISSUE THREAD

**Issue by zvezdochet2004** [Limych/ha-gismeteo#119]
**Is your feature request related to a problem? Please describe.**

no

**Describe the solution you'd like**

I would like to see pollen sensors for birch with a 10-day forecast

**Describe alternatives you've considered**

Pollen.com and IQWIA. This untegrations  supported only USA and GB. Russia do not supported

**Additional context**

example from website gismeteo.ru
![image](https://user-images.githubusercontent.com/78306956/166927349-280cfbdb-f7b0-44e2-9d13-d615b0c6afd7.png)

**Comment by d8rt8v** [comment]
Really needed feature

**Comment by Limych** [comment]
Added to v3.0
