### ISSUE TITLE
Good day. I really wanted to see the temperature of water in this integration 

### ISSUE THREAD

**Issue by alexejnic** [Limych/ha-gismeteo#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Limych** [comment]
I'm sorry, but only the information that is already provided by the component is available through the Gismeteo API. There is nothing extra there. As well as there is no way to show anything additional in the weather object.

**Comment by Limych** [comment]
**Note:** This is only in the development version so far. Be patient.
