### ISSUE TITLE
How to remove Gismeteo icon from map?

### ISSUE THREAD

**Issue by vlad36N** [Limych/ha-gismeteo#134]
**Environment**

- Home Assistant Core release with the issue: Home Assistant 2022.7.6
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): 
- Supervisor 2022.07.0 
- Operating System 8.2 
- Frontend 20220707.1 - latest 

**Describe the bug**

How to remove Gismeteo icon from map?

**Configuration.yaml**
```yaml

Not using config file, only UI

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Nothing in a log file

```

**Additional context**

**Comment by vlad36N** [comment]
Same on AirVisual:
![air_visual](https://user-images.githubusercontent.com/30022288/180642324-36b6bafb-beea-49ca-ad4c-dd40c82df8f2.png)

https://github.com/home-assistant/core/tree/dev/homeassistant/components/airvisual

**Comment by Limych** [comment]
Thanks :heart:
