### ISSUE TITLE
Интеграция gismeteo использует устаревший прогноз

### ISSUE THREAD

**Issue by sirenkovv** [Limych/ha-gismeteo#158]
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by dim0nf** [comment]
https://github.com/Limych/ha-gismeteo/issues#:~:text=yesterday%20by%20sirenkovv-,After%20updating%20Home%20Assistant%202023.9.0%2C%20there%20was%20a%20change%20of%20weather%20entities%2C%20an%20integration%20correction%20is%20needed.,-bug
