### ISSUE TITLE
GISMETEO in Home Assistant will stop work with version 2024.3.0

### ISSUE THREAD

**Issue by Goodgabs** [Limych/ha-gismeteo#165]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Gismeteo Integration Uses Deprecated Forecasting This stops working in version 2024.3.0. 
Fix the issue before upgrading. 
The gismeteo integration uses the deprecated forecast attribute. 
Please report it to the custom integration author..

### Describe the solution you'd like

update

### Describe alternatives you've considered

other integration

### Additional context

![image](https://github.com/Limych/ha-gismeteo/assets/134603303/32cbb3d0-77a8-4852-8ff5-b3db55f597b0)

**Comment by Goodgabs** [comment]
L'integrazione personalizzata gismeteo utilizza previsioni meteo obsolete
Questo smette di funzionare nella versione 2024.3.0. Risolvi il problema prima di effettuare l'aggiornamento.
L'integrazione personalizzata gismeteo implementa la proprietà forecast o imposta self._attr_forecast in una sottoclasse di WeatherEntity.

Crea una segnalazione di bug su https://github.com/Limych/ha-gismeteo/issues.

Una volta disponibile una versione aggiornata di gismeteo, installala e riavvia Home Assistant per risolvere questo problema.

**Comment by iqubik** [comment]
![image](https://github.com/Limych/ha-gismeteo/assets/22661808/a8f2e769-fdd6-4a1e-9c04-660b22662041)

**Comment by gilder0** [comment]
You can try my https://github.com/Limych/ha-gismeteo/pull/185
