### ISSUE TITLE
Cannot register a bug here

### ISSUE THREAD

**Issue by ildar170975** [Limych/ha-gismeteo#180]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The "issues" section only contains a "Feature request" button:

![image](https://github.com/Limych/ha-gismeteo/assets/71872483/ec3f877b-dd09-4067-8001-4aa0f2b78396)

### Describe the solution you'd like

A possibility to register a bug.

### Describe alternatives you've considered

none

### Additional context

none

**Comment by Limych** [comment]
Fixed
