### ISSUE TITLE
Gismeteo не работает через службу weather.get_forecasts

### ISSUE THREAD

**Issue by Pro100x3mal** [Limych/ha-gismeteo#184]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

При попытке вызвать службу данных о погоде weather.get_forecasts - gismeteo не отображается в списке доступных. Соответственно, прогноз  gismeteo не отображается в кастомной карте Weather Chart Card (https://github.com/mlamberts78/weather-chart-card/issues).

![IMG_4513](https://github.com/Limych/ha-gismeteo/assets/87969152/ec1ecf65-3b9b-469a-8905-5f1866902c8a)

Также в журнале сервера есть предупреждения об устаревших атрибутах:

![IMG_4515](https://github.com/Limych/ha-gismeteo/assets/87969152/70111a93-3e08-40a6-aacc-e42c257f94fc)
![IMG_4516](https://github.com/Limych/ha-gismeteo/assets/87969152/d29df5b8-e1fd-48b9-b067-06e3154bec97)

### Describe the solution you'd like

Было бы супер, если бы gismeteo обновился до версии 3, с новыми изменениями, которые позволят полноценно использовать эту интеграцию

### Describe alternatives you've considered

Xxx

### Additional context

Xxx

**Comment by Switch2002** [comment]
По рекомендации из этого сообщения [https://github.com/Limych/ha-gismeteo/pull/185#issue-2141203238](url) обновил файлы api.py, sensor.py и weather.py. Заменил файлы в /config/custom_components/gismeteo, перезагрузил HA и все заработало. 
Взял файлы здесь [https://github.com/gilder0/ha-gismeteo/tree/HA2023.9/custom_components/gismeteo](url)

Как временное решение пока не поправят в основной ветке думаю пойдет.
