### ISSUE TITLE
Error fetching gismeteo data: Invalid response from Gismeteo API: 403

### ISSUE THREAD

**Issue by soulripper13** [Limych/ha-gismeteo#201]
## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Asia/Vladivostok
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4969
Installed Version | 1.34.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 24
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 5.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), go2rtc (1.9.4), Music Assistant (2.0.7), Speedtest (1.6.2), Hass.io Access Point (0.5.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 15
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 6, 2024 at 2:28 AM
-- | --
current_recorder_run | July 16, 2024 at 1:46 PM
estimated_db_size | 20.71 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-gismeteo/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

This error originated from a custom integration.

Logger: custom_components.gismeteo
Source: helpers/update_coordinator.py:344
integration: Gismeteo (documentation, issues)
First occurred: 1:46:30 PM (10 occurrences)
Last logged: 1:54:42 PM

Error fetching gismeteo data: Invalid response from Gismeteo API: 403

### Reproduction steps

1.It was working. Then i started getting that. Have been using it for almost half a year without issues.
2.
3.
...

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.gismeteo
Source: helpers/update_coordinator.py:344
integration: Gismeteo (documentation, issues)
First occurred: 1:46:30 PM (10 occurrences)
Last logged: 1:54:42 PM

Error fetching gismeteo data: Invalid response from Gismeteo API: 403
```

**Comment by Limych** [comment]
Not a bug

**Comment by sghnsk** [comment]
When i try to open https://www.gismeteo.ru/weather-ozerny-179506/10-days/ the browser checks Cloudflare, but if my request this URL through the script/wget, it returns 403
```
2024-07-22 14:28:37.595 DEBUG (MainThread) [custom_components.gismeteo.api] Requesting URL https://www.gismeteo.ru/weather-ozerny-179506/10-days/
2024-07-22 14:28:42.687 ERROR (MainThread) [custom_components.gismeteo] Error fetching gismeteo data: Invalid response from Gismeteo API: 403
```
Although https://services.gismeteo.ru/inform-service/inf_chrome/forecast/?city=179506&lang=en opens without problems

How to bypass/fix this?
