### ISSUE TITLE
Error fetching data from Gismeteo - Status Code 403

### ISSUE THREAD

**Issue by danteblank** [Limych/ha-gismeteo#202]
## System Information

version | core-2024.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4595
Installed Version | 1.34.0
Stage | running
Available Repositories | 1386
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 58.0 GB
disk_used | 7.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Zigbee2MQTT (1.39.0-1), File editor (5.8.0), SQLite Web (4.2.0), ZigStar TI CC2652P/P7 FW Flasher (0.4.0), EMQX (0.6.1), Terminal & SSH (9.14.0), RPC Shutdown (2.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 16
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 июля 2024 г. в 18:51
-- | --
current_recorder_run | 21 июля 2024 г. в 21:19
estimated_db_size | 72.18 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-gismeteo/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

I receive this error on plugin start/restart. No data could be fetched. Seems like they changed something (maybe cloudflare is a problem now)
Error fetching gismeteo data: Invalid response from Gismeteo API: 403

### Reproduction steps

1. Just trying to start plugin

### Debug logs

```text
None
```

**Comment by Limych** [comment]
It's not an integration bug
