### ISSUE TITLE
Invalid response from Gismeteo API: 504

### ISSUE THREAD

**Issue by WRLPDZ** [Limych/ha-gismeteo#208]
## System Information

version | core-2024.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1492
Downloaded Repositories | 284

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 38

</details>

<details><summary>Airly</summary>

can_reach_server | ok
-- | --
requests_remaining | 11
requests_per_day | 100

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 15 października 2024 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
instance_id | 36db3622da3f4e7194276a89898aa21d
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 234.0 GB
disk_used | 36.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.7.1), RPC Shutdown (2.5), Samba share (12.3.2), ESPHome (2024.9.1), Advanced SSH & Web Terminal (19.0.0), InfluxDB (5.0.0), motionEye (0.20.0), Studio Code Server (5.16.0), Home Assistant Google Drive Backup (0.112.1), SQLite Web (4.2.1), Whisper (2.1.2), Piper (1.5.2), openWakeWord (1.10.0), Mosquitto broker (6.4.1), Network UPS Tools (0.13.2), Zigbee2MQTT (1.40.1-1), Vaultwarden (Bitwarden) (0.23.0), Firefox (1.2.0), Glances (0.21.1), Let's Encrypt (5.2.1), NGINX Home Assistant SSL proxy (3.10.1), Calibre (7.19.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 49
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 września 2024 20:58
-- | --
current_recorder_run | 28 września 2024 23:05
estimated_db_size | 551.18 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-gismeteo/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Gismeteo plugin is not working.
Error in logs custom_components.gismeteo.api.ApiError: Invalid response from Gismeteo API: 504
I have found that gismeteo.com is now meteofor.com.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Rejestrator: homeassistant.config_entries
Źródło: config_entries.py:604
Pierwsze zdarzenie: 23:07:00 (1 zdarzenia)
Ostatnio zalogowany: 23:07:00

Error setting up entry Dom for gismeteo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gismeteo/__init__.py", line 152, in async_setup_entry
    coordinator = await _async_get_coordinator(hass, entry.entry_id, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gismeteo/__init__.py", line 121, in _async_get_coordinator
    await gismeteo.async_update_location()
  File "/config/custom_components/gismeteo/api.py", line 241, in async_update_location
    response = await self._async_get_data(url, cache_fname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gismeteo/api.py", line 218, in _async_get_data
    raise ApiError(f"Invalid response from Gismeteo API: {resp.status}")
custom_components.gismeteo.api.ApiError: Invalid response from Gismeteo API: 504
```

**Comment by Limych** [comment]
Not a component bug.
