### ISSUE TITLE
Погода из ниоткуда

### ISSUE THREAD

**Issue by ASergeyV** [Limych/ha-gismeteo#218]
### System Health details

Интеграция 3.1

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-gismeteo/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Собственно погода через 2 дня (на воскресенье) да и вообще прогноз показывается вообще не в городе, на сайте погода нормальная
![weather](https://github.com/user-attachments/assets/b5f29247-8f85-42a6-b055-c419af811a85)
![Screenshot_20241213-083907_Home Assistant](https://github.com/user-attachments/assets/09665911-b338-46df-986e-61b46c31e828)
![Screenshot_20241213-083954_Home Assistant](https://github.com/user-attachments/assets/4e47e592-487a-428c-8e13-44882a8d1ea5)
В конфиге строка с указанием более точных координат игнорируется

### Reproduction steps

Перезапускаем интеграцию, смотрим прогноз. Погода обновлена Х секунд назад

### Debug logs

```text
.
```

**Comment by Limych** [comment]
Координаты прогноза — это координаты метеостанции Гисметео, а не те, что указаны в конфиге.
Метеостанция выбирается по принципу ближайшего расположения к указанным в конфиге координатам. И, да, она может быть вне административных границ города. Это нормально.

Прогноз берётся с сервера Гисметео через их API. Любые претензии по содержимому прогноза, пожалуйста, к самому Гисметео.

Если Вы считаете, что есть ошибка именно в самой интеграции, извольте, пожалуйста, предоставить Ваши конфиги и дебаг-лог, чтобы можно было увидеть ошибку и её повторить на тестовом сервере.
