### ISSUE TITLE
Кооординаты и точность прогноза

### ISSUE THREAD

**Issue by madspeed** [Limych/ha-gismeteo#219]
### System Health details

gismeteo 3.1.0
ha 2024.12.2

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-gismeteo/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Разница в погоде между сайтом и тем, как погоду выдает интеграция (при настройке интеграции указаны координаты этого же населенного пункта).
Понятно, что дело в координатах, но не понятно как это решить. И разница в погоде колоссальная, а не 0,5 градуса.
![image](https://github.com/user-attachments/assets/8b5fc159-150c-4e92-9e62-0413cadfc738)
![image](https://github.com/user-attachments/assets/7a92e36d-1d8d-432b-a75a-c7bcc41bce1b)
Спасибо!

### Reproduction steps

1.Установить интеграцию
2.Взять прогноз за сайта
3.
...

### Debug logs

```text
.
```

**Comment by Limych** [comment]
Не является багом интеграции.

Все вопросы — к Гисметео.
