### ISSUE TITLE
Возможность выбора единиц измерения давления и скорости ветра

### ISSUE THREAD

**Issue by conrad66** [Limych/ha-gismeteo#3]
Гисметео давление отдает в mmHg и скорость ветра в м/с
Сделайте пожалуйста возможность выбора единицы измерения, тем более в коде у вас эти значения присутствуют.
Не охота в ручную править ваш код.

**Comment by Limych** [comment]
Home Assistant принимает показатели давления ИСКЛЮЧИТЕЛЬНО в гектопаскалях. Именно поэтому в коде сенсора приходится конвертировать значения в эти единицы. Чтобы исправить ситуацию, нужно править не код этого сенсора, а код Home Assistant.
Буду рад, если Вы сможете убедить его создателей внести нужные изменения.
А пока этого не сделано, менять код этого сенсора нет никакого смысла, извините.

**Comment by Limych** [comment]
Результат (увы, плачевный) моей попытки добавить миллиметры ртутного столба в код HA: https://github.com/home-assistant/core/pull/35575
