### ISSUE TITLE
WARNING: Deprecated condition "weather". Please replace it to "condition"

### ISSUE THREAD

**Issue by fufar** [Limych/ha-gismeteo#36]
**Environment**

- Home Assistant Core release with the issue: 2021.3.4
- This custom component release with the issue: 2.2.0
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): 2021.3.4/supervisor-2021.03.9/Debian

**Describe the bug**

Get a warning message in log:
```
Logger: custom_components.gismeteo.sensor
Source: custom_components/gismeteo/sensor.py:98
Integration: Gismeteo (documentation, issues)
First occurred: 7 апреля 2021 г., 1:13:01 (1 occurrences)
Last logged: 7 апреля 2021 г., 1:13:01

Deprecated condition "weather". Please replace it to "condition"
```

**Comment by Limych** [comment]
It's not a bug. It's a message for you from this component to change your config due the config options where changed at last release.

Just open your config of this component and replace in `monitored_conditions` option «weather» to option «condition».  That's all.

The component's behavior will not change in any way. Only this warning will disappear.

But in the future releases, the old version of the options will be excluded from the configs.
