### ISSUE TITLE
После обновления на 108 НА поменялись иконки, и добавилась надпись High/Low

### ISSUE THREAD

**Issue by Hagakurje** [Limych/ha-gismeteo#4]
После обновления на 108 НА поменялись иконки, и добавилась надпись High/Low. Можно сделать так как было раньше? 
[image](https://ibb.co/B22PQSv)

**Comment by Limych** [comment]
Отображение контролируется самим HA, а не плагином. Плагин лишь предоставляет информацию.
Так что этот вопрос не по адресу, извините...
