### ISSUE TITLE
Support RU-ru language

### ISSUE THREAD

**Issue by dreem2001** [Limych/ha-gismeteo#61]
Добрый день.

Gismeteo умеет отдавать прогноз на русском и других языках через параметр `lang=ru` в запросе.
Есть ли возможность добавить поодержку языков, ну хотя бы русского? :)
Спасибо.

**Comment by Limych** [comment]
Любой язык, кроме наглицкого, внутри HA будет вызывать сбои. Потому значения прогноза ВСЕГДА будут отдаваться на нём.

При этом сенсоры давно локализованы и в интерфейсе переводятся автоматом на выбранный язык. Значение объекта weather также должно в интерфейсе переводиться. Но это уже забота самого HA.

Если у Вас нет перевода, скорее всего, у Вас давно устаревшие версия компонента. Просто обновите её.

PS. В следующий раз при игнорировании шаблона issue будет закрыто без комментариев. Шаблон придуман для облегчения моей работы, а не за ради развлечения.
