### ISSUE TITLE
Error sensor.gismeteo_rain

### ISSUE THREAD

**Issue by devmaster-st** [Limych/ha-gismeteo#94]
**Environment**

- Home Assistant Core release with the issue: core-2021.12.3
- This custom component release with the issue: 2.3.3
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Home Assistant Docker Container

**Describe the bug**
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 16:18:20 (10 occurrences)
Last logged: 16:18:20

Entity sensor.gismeteo_rain (<class 'custom_components.gismeteo.sensor.GismeteoSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.gismeteo_snow (<class 'custom_components.gismeteo.sensor.GismeteoSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.gismeteo_storm (<class 'custom_components.gismeteo.sensor.GismeteoSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.gismeteo_temperature (<class 'custom_components.gismeteo.sensor.GismeteoSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.gismeteo_wind_speed (<class 'custom_components.gismeteo.sensor.GismeteoSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Configuration.yaml**
```yaml

weather:
  - platform: gismeteo

```

**Steps to Reproduce**

**Expected behavior**
No errors or warnings.

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
Already fixed at v2.3.4

Thanks :heart:
